### ISSUE TITLE
Frederick - State change

### ISSUE THREAD

**Issue by akhkim** [akhkim/UofTrackMyGame#31]
Wishlist state change does not work with the rest of the code. The wishlist view works individually, but it is not prompted to open when the state change actually occurs with rest of the code.  

Check the state react used in ResultsView

![image](https://github.com/user-attachments/assets/cbf9acfa-5df2-45bb-b972-61299f48ae51)

**Comment by ycz425** [comment]
It works with the rest of the code now.
