### ISSUE TITLE
Enlarged Thumbnail

### ISSUE THREAD

**Issue by ycz425** [akhkim/UofTrackMyGame#39]
Some thumbnails are too big and pushes UI components off the panel. Is there a way to limit the size of the thumbnails?
To reduplicate problem: open game view for "Far Cry 5 Gold Edition".

**Comment by akhkim** [comment]
As the dimensions of the thumbnails differ for every game, it is difficult to limit the size of the thumbnails to a set value, however, I attempted an alternate fix, by changing the window size to match the size of the thumbnail by creating a new window. Please come back to me if this doesn't feel like the best solution. Thanks!

**Comment by akhkim** [comment]
I have further made it so it now checks for the original resolution of the thumbnail, and scales it down if too big.
