### ISSUE TITLE
Scrolling is Too Slow in ResultsView

### ISSUE THREAD

**Issue by bhavya-jain-364** [akhkim/UofTrackMyGame#53]
The scrolling experience in the ResultsView is currently too slow, which can hinder user interaction and make it difficult to browse through the results efficiently. This issue affects the overall usability of the application.

Proposed Changes:
Investigate the current implementation of the scrolling mechanism in the ResultsView.
Optimize the rendering of game results to improve scrolling performance.
Consider implementing lazy loading or pagination to enhance the user experience when dealing with a large number of results.

**Comment by akhkim** [comment]
Scrolling speed has now been adjusted. Now it should scroll 20 pixels at a time. Thank you for the input.
